<?php

/**
 * @file
 * Primary module hooks for Islandora IIIF hOCR module.
 */

 use Drupal\search_api\Query\QueryInterface;

 /**
  * Implementation of hook_islandora_manifest_alter().
  */
function islandora_iiif_hocr_islandora_iiif_manifest_alter(&$json, &$views_plugin) {
    // Sanity check that the hook is being invoked from the Views Template plugin.
    if (get_class($views_plugin) !== 'Drupal\islandora_iiif\Plugin\views\style\IIIFManifest') {
        Drupal::mmessenger()->addWarning("Hook islandora_iiif_manifest_alter parameter 2 not of type Drupal\islandora_iiif\Plugin\views\style\IIIFManifest");
        return;
    }

    $nid = $views_plugin->getRequest()->attributes->get('node');
    if (!$nid) {
        return;
    }

    $url_base = $views_plugin->getRequest()->getSchemeAndHttpHost();
    $hocr_search_path = \Drupal\Core\Url::fromRoute('islandora_iiif_hocr.hocr_search', ['node' => $nid])->toString();
    $hocr_search_url = $url_base . $hocr_search_path;
    $json['service'][] = [
          "@context" => "http://iiif.io/api/search/0/context.json",
          "@id" => $hocr_search_url,
          "profile" => "http://iiif.io/api/search/0/search",
          "label" => t("Search inside this work"),
    ];
}


/**
 * Implements hook_search_api_solr_query_alter().
 *
 * Add ocr highlight params into the solr query.
 *
 * It's a mystery as to why it should be necessary to alter the solarium query in order to add the
 * highlight parameters. We should be able to add them inside the search_api query build using the
 * `solr_param_` method to inject solarium parameters: https://git.drupalcode.org/project/search_api_solr/-/blob/4.x/src/Plugin/search_api/backend/SearchApiSolrBackend.php#L1605-1610
 * However that is not working, and so we're reduced to this ugly alter hook.
 *
 */
function islandora_iiif_hocr_search_api_solr_query_alter(SolariumQueryInterface $solarium_query, QueryInterface $query) {
    // To get a list of solarium events:
    // @see http://solarium.readthedocs.io/en/stable/customizing-solarium/#plugin-system
    if ($query->getOption('no_highlight')) {
      $solarium_query->addParam('hl', 'false');
      /* @var \Solarium\Component\Highlighting\Highlighting $hl */
      $hl = $solarium_query->getHighlighting();
      $hl->clearFields();
    }
  
    if ($query->getOption('ocr_highlight')) {
      /* @var \Solarium\Component\Highlighting\Highlighting $hl */
      $hl = $solarium_query->getHighlighting();
      $hl->clearFields();
  
      $solarium_query->addParam('hl.ocr.fl', $query->getOption('ocr_highlight'));
      $solarium_query->addParam('hl.ocr.absoluteHighlights', 'on');
      $solarium_query->addParam('hl.method', 'UnifiedHighlighter');
    }
  }
  